SnowfoxMkIIAirbases = {}
SnowfoxMkIIAirbases[1] = {}
SnowfoxMkIIAirbases[1]["Airbase"] = "Abu Dhabi Intl"
SnowfoxMkIIAirbases[1]["Coalition"] = 3
SnowfoxMkIIAirbases[2] = {}
SnowfoxMkIIAirbases[2]["Airbase"] = "Abu Musa Island"
SnowfoxMkIIAirbases[2]["Coalition"] = 1
SnowfoxMkIIAirbases[3] = {}
SnowfoxMkIIAirbases[3]["Airbase"] = "Al Ain Intl"
SnowfoxMkIIAirbases[3]["Coalition"] = 3
SnowfoxMkIIAirbases[4] = {}
SnowfoxMkIIAirbases[4]["Airbase"] = "Al-Bateen"
SnowfoxMkIIAirbases[4]["Coalition"] = 3
SnowfoxMkIIAirbases[5] = {}
SnowfoxMkIIAirbases[5]["Airbase"] = "Al Maktoum Intl"
SnowfoxMkIIAirbases[5]["Coalition"] = 3
SnowfoxMkIIAirbases[6] = {}
SnowfoxMkIIAirbases[6]["Airbase"] = "Bandar Abbas Intl"
SnowfoxMkIIAirbases[6]["Coalition"] = 1
SnowfoxMkIIAirbases[7] = {}
SnowfoxMkIIAirbases[7]["Airbase"] = "Bandar Lengeh"
SnowfoxMkIIAirbases[7]["Coalition"] = 1
SnowfoxMkIIAirbases[8] = {}
SnowfoxMkIIAirbases[8]["Airbase"] = "Bandar-e-Jask"
SnowfoxMkIIAirbases[8]["Coalition"] = 1
SnowfoxMkIIAirbases[9] = {}
SnowfoxMkIIAirbases[9]["Airbase"] = "Dubai Intl"
SnowfoxMkIIAirbases[9]["Coalition"] = 3
SnowfoxMkIIAirbases[10] = {}
SnowfoxMkIIAirbases[10]["Airbase"] = "Fujairah Intl"
SnowfoxMkIIAirbases[10]["Coalition"] = 1
SnowfoxMkIIAirbases[11] = {}
SnowfoxMkIIAirbases[11]["Airbase"] = "Havadarya"
SnowfoxMkIIAirbases[11]["Coalition"] = 1
SnowfoxMkIIAirbases[12] = {}
SnowfoxMkIIAirbases[12]["Airbase"] = "Khasab"
SnowfoxMkIIAirbases[12]["Coalition"] = 1
SnowfoxMkIIAirbases[13] = {}
SnowfoxMkIIAirbases[13]["Airbase"] = "Kish Intl"
SnowfoxMkIIAirbases[13]["Coalition"] = 1
SnowfoxMkIIAirbases[14] = {}
SnowfoxMkIIAirbases[14]["Airbase"] = "Lavan Island"
SnowfoxMkIIAirbases[14]["Coalition"] = 1
SnowfoxMkIIAirbases[15] = {}
SnowfoxMkIIAirbases[15]["Airbase"] = "Liwa AFB"
SnowfoxMkIIAirbases[15]["Coalition"] = 2
SnowfoxMkIIAirbases[16] = {}
SnowfoxMkIIAirbases[16]["Airbase"] = "Qeshm Island"
SnowfoxMkIIAirbases[16]["Coalition"] = 1
SnowfoxMkIIAirbases[17] = {}
SnowfoxMkIIAirbases[17]["Airbase"] = "Ras Al Khaimah Intl"
SnowfoxMkIIAirbases[17]["Coalition"] = 1
SnowfoxMkIIAirbases[18] = {}
SnowfoxMkIIAirbases[18]["Airbase"] = "Sas Al Nakheel"
SnowfoxMkIIAirbases[18]["Coalition"] = 2
SnowfoxMkIIAirbases[19] = {}
SnowfoxMkIIAirbases[19]["Airbase"] = "Sharjah Intl"
SnowfoxMkIIAirbases[19]["Coalition"] = 3
SnowfoxMkIIAirbases[20] = {}
SnowfoxMkIIAirbases[20]["Airbase"] = "Sir Abu Nuayr"
SnowfoxMkIIAirbases[20]["Coalition"] = 1
SnowfoxMkIIAirbases[21] = {}
SnowfoxMkIIAirbases[21]["Airbase"] = "Sirri Island"
SnowfoxMkIIAirbases[21]["Coalition"] = 1
SnowfoxMkIIAirbases[22] = {}
SnowfoxMkIIAirbases[22]["Airbase"] = "Tunb Island AFB"
SnowfoxMkIIAirbases[22]["Coalition"] = 1
SnowfoxMkIIAirbases[23] = {}
SnowfoxMkIIAirbases[23]["Airbase"] = "Tunb Kochak"
SnowfoxMkIIAirbases[23]["Coalition"] = 1
